## Jueves 23 de abril del 2026
## Julieta Madrigal Flores - 744029
## Actividad de árboles

In [1]:
import pandas as pd
import numpy as np

In [2]:
data={
    'genero':['H','M','H','H','H','H','H','H','H','M','M','H','H','H','H','H'],
    'edad':[21,19,21,19,20,21,22,21,19,21,19,21,20,20,19,19],
    'estatura':[1.73,1.62,1.73,1.69,1.75,1.8,1.7,1.75,1.66,1.64,1.62,1.85,1.75,1.66,1.7,1.64]
}

df=pd.DataFrame(data)
display(df)

   genero  edad  estatura
0       H    21      1.73
1       M    19      1.62
2       H    21      1.73
3       H    19      1.69
4       H    20      1.75
5       H    21      1.80
6       H    22      1.70
7       H    21      1.75
8       H    19      1.66
9       M    21      1.64
10      M    19      1.62
11      H    21      1.85
12      H    20      1.75
13      H    20      1.66
14      H    19      1.70
15      H    19      1.64

### Filtramos para que sean hombres con edad mayor o igual a 21

In [7]:
df_fil= df[(df['edad']>=21)&(df['genero']=='H')]
df_fil

   genero  edad  estatura
0       H    21      1.73
2       H    21      1.73
5       H    21      1.80
6       H    22      1.70
7       H    21      1.75
11      H    21      1.85

In [6]:
df_fil['estatura'].mean()

np.float64(1.76)

### Filtramos hombres menores a 21 años

In [9]:
df_menorH= df[(df['edad']<21)&(df['genero']=='H')]
df_menorH

   genero  edad  estatura
3       H    19      1.69
4       H    20      1.75
8       H    19      1.66
12      H    20      1.75
13      H    20      1.66
14      H    19      1.70
15      H    19      1.64

In [10]:
df_menorH['estatura'].mean()

np.float64(1.6928571428571428)

### Filtramos a las mujeres con 21 o más años

In [11]:
df_mayorM=df[(df['edad']>=21)&(df['genero']=='M')]
df_mayorM

  genero  edad  estatura
9      M    21      1.64

In [13]:
df_mayorM['estatura'].mean()

np.float64(1.64)

### Filtramos a las mujeres menores a 21

In [12]:
df_menorM=df[(df['edad']<21)&(df['genero']=='M')]
df_menorM

   genero  edad  estatura
1       M    19      1.62
10      M    19      1.62

In [14]:
df_menorM['estatura'].mean()

np.float64(1.62)

## **ACTIVIDAD**

## 1.Tomar el dataset de advertising y hacer una regresion lineal simple

In [15]:
dataset = pd.read_csv('Advertising.csv')
dataset.head()

   Unnamed: 0     TV  radio  newspaper  sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [18]:
# definir Y y X
y = dataset['sales']
x = dataset[['TV','radio','newspaper']]

In [20]:
from sklearn.linear_model import LinearRegression

In [21]:
lr = LinearRegression()
lr.fit(x, y)

LinearRegression()

## 2. Calcular R2

In [22]:
R2 = lr.score(x, y)
R2

0.8972106381789522

## 3.Usar 1 árbol de decisión para regresión sobre el mismo dataset

In [23]:
from sklearn.tree import DecisionTreeRegressor
DecisionTreeRegressor = DecisionTreeRegressor()
DecisionTreeRegressor.fit(x, y)

DecisionTreeRegressor()

## 4. Calcular R2

In [24]:
R2_tree = DecisionTreeRegressor.score(x, y)
R2_tree

1.0

## 5.Repetir ( 1- 4) con train-test al 50/50

In [25]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=42)

### *Con árboles*

In [28]:
# Árboles con train / test split
from sklearn.tree import DecisionTreeRegressor
DecisionTreeRegressor50 = DecisionTreeRegressor()
DecisionTreeRegressor50.fit(X_train, y_train)

DecisionTreeRegressor()

In [31]:
# R2 en Train con árbol
R2_tree_train = DecisionTreeRegressor50.score(X_train, y_train)
R2_tree_train

1.0

In [32]:
# R2 en Test con árbol
R2_tree_test = DecisionTreeRegressor50.score(X_test, y_test)
R2_tree_test

0.9380919195424385

### *Con regresión*

In [33]:
# Hacemos regresión con Train/Test
lr2 = LinearRegression()
lr2.fit(X_train, y_train)

LinearRegression()

In [34]:
# Calculamos el R2 de train
R2_train = lr2.score(X_train, y_train)
R2_train

0.9042613648908893

In [35]:
# Calculamos el R2 de test
R2_test = lr2.score(X_test, y_test)
R2_test

0.8721004816045135